### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-stt-http-server#9]
When selecting language I got this error:

![image](https://github.com/OpenVoiceOS/ovos-stt-http-server/assets/614115/5443a0f3-ce25-4ace-b351-de56e8efffc5)

```
INFO:     192.168.1.227:55622 - "POST /run/predict HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_stt_http_server/gradio_app.py", line 12, in transcribe
    with open(audio_file, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by NeonDaniel** [comment]
Ah, looks like this needs a check that the file exists for that language
